# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: friday
      time: '06:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - patch
          - minor
      major:
        update-types:
          - major
    labels:
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: friday
      time: '06:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ['*']
    labels:
      - 'actions'
