/**
 * Device Entity.
 *
 * @property {string} id Unique ID of a device (generated by Home Assistant).
 * @property {string[]} config_entries Config entries that are linked to this device.
 * @property {Record<string, (string | null)[]>} config_entries_subentries
 * @property {[string, string][]} connections A set of tuples of (connection_type, connection identifier).
 *                                            Connection types are defined in the device registry module.
 *                                            Each item in the set uniquely defines a device entry, meaning another
 *                                            device can't have the same connection.
 * @property {[string, string][]} identifiers Set of (DOMAIN, identifier) tuples.
 *                                            Identifiers identify the device in the outside world.
 *                                            An example is a serial number.
 *                                            Each item in the set uniquely defines a device entry, meaning another
 *                                            device can't have the same identifier.
 * @property {string | null} manufacturer The manufacturer of the device.
 * @property {string | null} model The model name of the device.
 * @property {string | null} model_id The model identifier of the device.
 * @property {string | null} name Name of this device
 * @property {string[]} labels
 * @property {string | null} sw_version The firmware version of the device.
 * @property {string | null} hw_version The hardware version of the device.
 * @property {string | null} serial_number The serial number of the device.
 *                                         Unlike a serial number in the identifiers set, this does not need to be
 *                                         unique.
 * @property {string | null} via_device_id Identifier of a device that routes messages between this device and Home Assistant.
 *                                         Examples of such devices are hubs, or parent devices of a sub-device.
 *                                         This is used to show device topology in Home Assistant.
 * @property {string} area_id The Area which the device is placed in.
 * @property {string | null} name_by_user The user configured name of the device.
 * @property {string[] | null} entry_type The type of entry. Possible values are None and DeviceEntryType enum members
 *                                        (only service).
 * @property {string | null} disabled_by Indicates by what this entity is disabled.
 * @property {string | null} configuration_url A URL on which the device or service can be configured,
 *                                             linking to paths inside the Home Assistant UI can be done by using
 *                                             homeassistant://<path>.
 * @property {string | null} primary_config_entry
 */
export interface DeviceRegistryEntry {
  id: string;
  config_entries: string[];
  config_entries_subentries: Record<string, (string | null)[]>;
  connections: [string, string][];
  identifiers: [string, string][];
  manufacturer: string | null;
  model: string | null;
  model_id: string | null;
  name: string | null;
  labels: string[];
  sw_version: string | null;
  hw_version: string | null;
  serial_number: string | null;
  via_device_id: string | null;
  area_id: string | null;
  name_by_user: string | null;
  entry_type: "service" | null;
  disabled_by: "user" | "integration" | "config_entry" | null;
  configuration_url: string | null;
  primary_config_entry: string | null;
}
